[book]
authors = ["Nicolas Mohnblatt"]
language = "en"
multilingual = false
src = "src"
title = "ZK Jargon Decoder"

[preprocessor.katex]
renderers = ["html"]

[output.katex]

[output.html]
curly-quotes = true
no-section-label = true
git-repository-url = "https://github.com/nmohnblatt/zk-jargon-decoder"
edit-url-template = "https://github.com/nmohnblatt/zk-jargon-decoder/src/{path}"

[output.html.print]
page-break = false
