[book]
authors = ["Nicolas Mohnblatt"]
language = "en"
multilingual = true
src = "src"
title = "ZK Jargon Decoder"

[preprocessor.katex]
renderers = ["html"]

[preprocessor.gettext]
after = ["links"]

[output.katex]

[output.html]
smart-punctuation = true
no-section-label = true
git-repository-url = "https://github.com/nmohnblatt/zk-jargon-decoder"

[output.html.print]
page-break = false

[build]
extra-watch-dirs = ["po"]
